### ISSUE TITLE
Eventbrite does not have a registration button

### ISSUE THREAD

**Issue by noamross** [camillescott/2015-08-16-ucdavis-wise#4]
Looking at the site, I only see a place for the promotional code, no registration button:

![screenshot 2015-07-23 13 59 04](https://cloud.githubusercontent.com/assets/571752/8862110/05109e82-3143-11e5-829b-bce6eb126c2c.png)

Is the idea for registrants to get a code via e-mail?  I wanted to check before disseminating this more broadly.  Thanks!

@Myfanwy

**Comment by camillescott** [comment]
Fixed by proper activation of the eventbrite event.
